# Generated by Django 5.0.2 on 2024-02-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0002_tasks_priority_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='last_name',
        ),
    ]
