# Generated by Django 5.0.2 on 2024-02-23 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0004_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 10, 50, 16, 486955, tzinfo=datetime.timezone.utc)),
        ),
    ]
