# Generated by Django 5.0.2 on 2024-02-23 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0005_tasks_my_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 10, 51, 51, 77841, tzinfo=datetime.timezone.utc)),
        ),
    ]
