# Generated by Django 5.0.2 on 2024-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0006_alter_tasks_my_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='my_date',
            field=models.DateTimeField(),
        ),
    ]
