# Generated by Django 5.0.2 on 2024-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0008_remove_tasks_my_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateField(default='25-02-2023'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='HomeWork', max_length=20),
        ),
    ]
