# Generated by Django 5.0.2 on 2024-02-23 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0010_alter_tasks_created_at_alter_tasks_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=datetime.date(2024, 2, 23))),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 2, 23)),
        ),
    ]
