# Generated by Django 5.0.2 on 2024-02-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0011_tasklist_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trelloapp.tasklist'),
        ),
    ]
