# Generated by Django 5.0.2 on 2024-02-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0013_alter_tasklist_created_at_alter_tasks_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='High', max_length=20, null=True),
        ),
    ]
